// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: ssh.proto

package sshpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SSHRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`     // pode ser vazio se usar chave
	PrivateKey    string                 `protobuf:"bytes,5,opt,name=privateKey,proto3" json:"privateKey,omitempty"` // opcional
	Command       string                 `protobuf:"bytes,6,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHRequest) Reset() {
	*x = SSHRequest{}
	mi := &file_ssh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHRequest) ProtoMessage() {}

func (x *SSHRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ssh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHRequest.ProtoReflect.Descriptor instead.
func (*SSHRequest) Descriptor() ([]byte, []int) {
	return file_ssh_proto_rawDescGZIP(), []int{0}
}

func (x *SSHRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SSHRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SSHRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SSHRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SSHRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *SSHRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type SSHResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exitCode,proto3" json:"exitCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHResponse) Reset() {
	*x = SSHResponse{}
	mi := &file_ssh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHResponse) ProtoMessage() {}

func (x *SSHResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ssh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHResponse.ProtoReflect.Descriptor instead.
func (*SSHResponse) Descriptor() ([]byte, []int) {
	return file_ssh_proto_rawDescGZIP(), []int{1}
}

func (x *SSHResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *SSHResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *SSHResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_ssh_proto protoreflect.FileDescriptor

const file_ssh_proto_rawDesc = "" +
	"\n" +
	"\tssh.proto\x12\n" +
	"sshService\"\x9e\x01\n" +
	"\n" +
	"SSHRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1e\n" +
	"\n" +
	"privateKey\x18\x05 \x01(\tR\n" +
	"privateKey\x12\x18\n" +
	"\acommand\x18\x06 \x01(\tR\acommand\"Y\n" +
	"\vSSHResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1a\n" +
	"\bexitCode\x18\x03 \x01(\x05R\bexitCode2E\n" +
	"\x03SSH\x12>\n" +
	"\vExecCommand\x12\x16.sshService.SSHRequest\x1a\x17.sshService.SSHResponseB\x0fZ\rsshgrpc/sshpbb\x06proto3"

var (
	file_ssh_proto_rawDescOnce sync.Once
	file_ssh_proto_rawDescData []byte
)

func file_ssh_proto_rawDescGZIP() []byte {
	file_ssh_proto_rawDescOnce.Do(func() {
		file_ssh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ssh_proto_rawDesc), len(file_ssh_proto_rawDesc)))
	})
	return file_ssh_proto_rawDescData
}

var file_ssh_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ssh_proto_goTypes = []any{
	(*SSHRequest)(nil),  // 0: sshService.SSHRequest
	(*SSHResponse)(nil), // 1: sshService.SSHResponse
}
var file_ssh_proto_depIdxs = []int32{
	0, // 0: sshService.SSH.ExecCommand:input_type -> sshService.SSHRequest
	1, // 1: sshService.SSH.ExecCommand:output_type -> sshService.SSHResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ssh_proto_init() }
func file_ssh_proto_init() {
	if File_ssh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ssh_proto_rawDesc), len(file_ssh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ssh_proto_goTypes,
		DependencyIndexes: file_ssh_proto_depIdxs,
		MessageInfos:      file_ssh_proto_msgTypes,
	}.Build()
	File_ssh_proto = out.File
	file_ssh_proto_goTypes = nil
	file_ssh_proto_depIdxs = nil
}
