// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: ssh.proto

package sshpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SSH_ExecCommand_FullMethodName = "/sshService.SSH/ExecCommand"
)

// SSHClient is the client API for SSH service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SSHClient interface {
	// Executa um comando único via SSH
	ExecCommand(ctx context.Context, in *SSHRequest, opts ...grpc.CallOption) (*SSHResponse, error)
}

type sSHClient struct {
	cc grpc.ClientConnInterface
}

func NewSSHClient(cc grpc.ClientConnInterface) SSHClient {
	return &sSHClient{cc}
}

func (c *sSHClient) ExecCommand(ctx context.Context, in *SSHRequest, opts ...grpc.CallOption) (*SSHResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSHResponse)
	err := c.cc.Invoke(ctx, SSH_ExecCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SSHServer is the server API for SSH service.
// All implementations must embed UnimplementedSSHServer
// for forward compatibility.
type SSHServer interface {
	// Executa um comando único via SSH
	ExecCommand(context.Context, *SSHRequest) (*SSHResponse, error)
	mustEmbedUnimplementedSSHServer()
}

// UnimplementedSSHServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSSHServer struct{}

func (UnimplementedSSHServer) ExecCommand(context.Context, *SSHRequest) (*SSHResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecCommand not implemented")
}
func (UnimplementedSSHServer) mustEmbedUnimplementedSSHServer() {}
func (UnimplementedSSHServer) testEmbeddedByValue()             {}

// UnsafeSSHServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SSHServer will
// result in compilation errors.
type UnsafeSSHServer interface {
	mustEmbedUnimplementedSSHServer()
}

func RegisterSSHServer(s grpc.ServiceRegistrar, srv SSHServer) {
	// If the following call panics, it indicates UnimplementedSSHServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SSH_ServiceDesc, srv)
}

func _SSH_ExecCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSHServer).ExecCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SSH_ExecCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSHServer).ExecCommand(ctx, req.(*SSHRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SSH_ServiceDesc is the grpc.ServiceDesc for SSH service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SSH_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sshService.SSH",
	HandlerType: (*SSHServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecCommand",
			Handler:    _SSH_ExecCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ssh.proto",
}
